### ISSUE TITLE
App stop working when clicking in some options

### ISSUE THREAD

**Issue by ronebrandao** [rhysma/SpaceLaunchApp#1]

**Comment by TiffanyFord** [comment]
I put this together for a Xamarin demo about a year ago. It's not something I maintain and I wouldn't expect it to work anymore since Xamarin has updated.

**Comment by ronebrandao** [comment]
I was not complayning about the app. My intention was to add something like a backlog haha, I'm a new GitHub user. But when I noticed what it is, I couldn't find a way to delete this issue. You will accept pull requests to it? I'm currently fixing it and adding some features. It was a good move for me, since I'm learning Xamarin now.

**Comment by rhysma** [comment]
Sure
